version: '3'
services:
  # locust-master:
  #   build: .
  #   command: locust -f iot-publish.py -H 10.50.11.160:30002 --master
  #   volumes:
  #     - .:/usr/src/app
  #   ports:
  #     - 8089:8089
  #     - 5557:5557
  locust-slave:
    build: .
    command: locust -f iot-publish.py --slave --master-host=10.202.70.18
    volumes:
      - .:/usr/src/app
    # depends_on:
    #   - locust-master
  