version: '3'
services:
  # locust-master:
  #   image: locust-mqtt-1
  #   command: locust -f iot-publish.py -H iotmid-docker.cpqd.com.br:1883 --master
  #   ports:
  #     - 8089:8089
  locust-slave:
    image: locust-mqtt-1
    command: locust -f iot-publish.py --slave --master-host=10.202.71.190