version: '3'
services:
  locust-master:
    build: .
    #command: locust -f iot-publish.py -H 10.50.11.160:30002 --master
    command: locust -f iot-publish.py -H 10.4.2.28:1883 --master
    volumes: 
      - .:/usr/src/app
    ports:
      - 8089:8089
  locust-slave:
    build: .
    command: locust -f iot-publish.py --slave --master-host=locust-master
    volumes: 
      - .:/usr/src/app
    depends_on:
      - locust-master
  # locust-normal:
  #   build: .
  #   command: locust -f iot-publish.py -H 10.4.2.28:1883 --no-web -c 1000 -r 10