version: '3'
services:
  locust-master:
    image: locust-mqtt-1
    #command: locust -f iot-publish.py -H 10.50.11.160:30002 --master
    command: locust -f iot-publish.py -H 10.4.2.28:1883 --master
    ports:
      - 8089:8089
  locust-slave:
    image: locust-mqtt-1
    command: locust -f iot-publish.py --slave --master-host=locust-master
    depends_on:
      - locust-master
  